// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCpAlHYuBgF4zjNda5hl1Aq3mIEylTVbI',
    appId: '1:1026100608814:web:1f186fcebc9fc2b6aa84bf',
    messagingSenderId: '1026100608814',
    projectId: 'yoyo-df823',
    authDomain: 'yoyo-df823.firebaseapp.com',
    storageBucket: 'yoyo-df823.appspot.com',
    measurementId: 'G-D84VX5F0D7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK7YvZvQW0owh39wXe7SAMFEaCZQRplho',
    appId: '1:1026100608814:android:b2c6759ab6ce9884aa84bf',
    messagingSenderId: '1026100608814',
    projectId: 'yoyo-df823',
    storageBucket: 'yoyo-df823.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2nwauICZtNikTzvt4GlERjpovORph2Js',
    appId: '1:1026100608814:ios:1ad28440eff1e1dfaa84bf',
    messagingSenderId: '1026100608814',
    projectId: 'yoyo-df823',
    storageBucket: 'yoyo-df823.appspot.com',
    androidClientId: '1026100608814-ohl05p8a38mdb8pkhste020jeb129duq.apps.googleusercontent.com',
    iosClientId: '1026100608814-e7cu7mg129smjikulna80m2o8jsttd5c.apps.googleusercontent.com',
    iosBundleId: 'com.example.anotherrecipeappp',
  );
}
